template: testify
packages:
    github.com/amirasaad/fintech/pkg/repository:
        config:
            dir: "internal/fixtures"
            filename: "mocks.go"
            pkgname: "fixtures"
            structname: "Mock{{.InterfaceName}}"
        interfaces:
          TransactionRepository:
          AccountRepository:
          UserRepository:
          UnitOfWork:
