template: testify
packages:
    github.com/amirasaad/fintech/pkg/repository:
        config:
            dir: "internal/fixtures"
            filename: "repository.go"
            pkgname: "fixtures"
            structname: "Mock{{.InterfaceName}}"
        interfaces:
            TransactionRepository:
            AccountRepository:
            UserRepository:
            UnitOfWork:
    github.com/amirasaad/fintech/pkg/service:
        config:
            dir: "internal/fixtures"
            filename: "service.go"
            pkgname: "fixtures"
            structname: "Mock{{.InterfaceName}}"
        interfaces:
            AuthStrategy:
    github.com/amirasaad/fintech/pkg/domain:
        config:
            dir: "internal/fixtures"
            filename: "domain.go"
            pkgname: "fixtures"
            structname: "Mock{{.InterfaceName}}"
        interfaces:
            CurrencyConverter:
