template: testify
packages:
  github.com/amirasaad/fintech/pkg/repository:
    config:
      dir: "internal/fixtures/mocks"
      filename: "uow.go"
      pkgname: "mocks"
      structname: "{{.InterfaceName}}"
    interfaces:
      UnitOfWork:
  github.com/amirasaad/fintech/pkg/repository/account:
    config:
      dir: "internal/fixtures/mocks"
      filename: "account.go"
      pkgname: "mocks"
      structname: "Account{{.InterfaceName}}"
    interfaces:
      Repository:
  github.com/amirasaad/fintech/pkg/repository/transaction:
    config:
      dir: "internal/fixtures/mocks"
      filename: "transaction.go"
      pkgname: "mocks"
      structname: "Transaction{{.InterfaceName}}"
    interfaces:
      Repository:
  github.com/amirasaad/fintech/pkg/repository/user:
    config:
      dir: "internal/fixtures/mocks"
      filename: "user.go"
      pkgname: "mocks"
      structname: "User{{.InterfaceName}}"
    interfaces:
      Repository:
  github.com/amirasaad/fintech/pkg/service/auth:
    config:
      dir: "internal/fixtures/mocks"
      filename: "auth.go"
      pkgname: "mocks"
      structname: "{{.InterfaceName}}"
    interfaces:
      Strategy:
  github.com/amirasaad/fintech/pkg/domain:
    config:
      dir: "internal/fixtures/mocks"
      filename: "domain.go"
      pkgname: "mocks"
      structname: "{{.InterfaceName}}"
    interfaces:
      CurrencyConverter:
  github.com/amirasaad/fintech/pkg/eventbus:
    config:
      dir: "internal/fixtures/mocks"
      filename: "eventbus.go"
      pkgname: "mocks"
      structname: "{{.InterfaceName}}"
    interfaces:
      Bus:
  github.com/amirasaad/fintech/pkg/provider:
    config:
      dir: "internal/fixtures/mocks"
      pkgname: "mocks"
    interfaces:
      ExchangeRateProvider:
      PaymentProvider:
  github.com/amirasaad/fintech/pkg/registry:
    config:
      dir: "internal/fixtures/mocks"
      filename: "registry.go"
      pkgname: "mocks"
      structname: "Registry{{.InterfaceName}}"
    interfaces:
      Provider:
