repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: local
    hooks:
      - id: event-cycle-check
        name: "event cycle check"
        entry: ./scripts/event_cycle_check.go
        pass_filenames: false
        types: [bash]
        language: system
      - id: go-vet
        name: "go run vet"
        entry: go vet ./...
        pass_filenames: false
        types: [go]
        language: system
      - id: go-unit-tests
        name: "run unit tests"
        entry: go test -p 12 ./pkg/...
        pass_filenames: false
        types: [go]
        language: system
      - id: go-critic
        name: "gocritic check"
        entry: gocritic check ./...
        pass_filenames: false
        types: [go]
        language: system
      - id: golangci-lint
        name: "golangci-lint"
        entry: golangci-lint run
        pass_filenames: false
        types: [go]
        language: system
      - id: go-build
        name: "go build"
        entry: go build ./...
        pass_filenames: false
        types: [go]
        language: system
      - id: go-test
        name: "go test"
        entry: go test ./pkg/...
        pass_filenames: false
        types: [go]
        language: system
      - id: go-fmt
        name: go go-fmt
        entry: go fmt ./...
        pass_filenames: false
        types: [go]
        language: system
      - id: go-mod
        name: go mod tidy
        entry: go mod tidy
        pass_filenames: false
        types: [go]
        language: system
