repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - entry: ./scripts/event_cycle_check.go
    id: event-cycle-check
    language: system
    name: event cycle check
    pass_filenames: false
    types:
    - bash
  - entry: go vet ./...
    id: go-vet
    language: system
    name: go run vet
    pass_filenames: false
    types:
    - go
  - entry: go test -p 12 ./pkg/...
    id: go-unit-tests
    language: system
    name: run unit tests
    pass_filenames: false
    types:
    - go
  - entry: gocritic check ./...
    id: go-critic
    language: system
    name: gocritic check
    pass_filenames: false
    types:
    - go
  - entry: golangci-lint run
    id: golangci-lint
    language: system
    name: golangci-lint
    pass_filenames: false
    types:
    - go
  - entry: go build ./...
    id: go-build
    language: system
    name: go build
    pass_filenames: false
    types:
    - go
  - entry: go test ./pkg/...
    id: go-test
    language: system
    name: go test
    pass_filenames: false
    types:
    - go
  - entry: go fmt ./...
    id: go-fmt
    language: system
    name: go go-fmt
    pass_filenames: false
    types:
    - go
  - entry: go mod tidy
    id: go-mod
    language: system
    name: go mod tidy
    pass_filenames: false
    types:
    - go
  repo: local
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.3
