site_name: Fintech Docs
repo_url: https://github.com/amirasaad/fintech
site_url: https://amirasaad.github.io/fintech/
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
      primary: black
      accent: pink
      scheme: slate
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.instant.preview
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.footnote.tooltips
    - content.code.select
    - content.code.copy

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - admonition

plugins:
  - search
  - tags
  - offline
  - blog
  - swagger-ui-tag

extra:
  version:
    default: stable

nav:
  - Home:
    - index.md
    - Getting Started: getting-started.md
    - Project Structure: project-structure.md
    - Architecture & Design: architecture.md
    - Service ↔ Domain Communication: service-domain-communication.md
    - API Usage: api-usage.md
    - Testing: testing.md
    - Examples: examples.md
  - Currency & Exchange:
    - currency/index.md
    - Currency System: currency/currency-system.md
    - Exchange Rates: currency/exchange-rates.md
    - Multi-Currency: currency/multi-currency.md
  - Payments:
    - payments/index.md
    - Event-Driven Payments: payments/event-driven-payments.md
    - Stripe Integration: payments/stripe-integration.md
  - Refactoring:
    - refactoring/index.md
    - Patterns:
      - refactoring/patterns.md
      - Decorator Pattern: refactoring/decorator-pattern.md
      - UOW Pattern: refactoring/uow-pattern.md
    - CQRS:
      - Transaction CQRS Refactor: refactoring/transaction-cqrs-refactor.md
      - Transaction Persistence Refactor: refactoring/transaction-persistence-refactor.md
    - Event-Driven:
      - Architecture: refactoring/event-driven-architecture.md
      - Account Service: refactoring/account-service.md
      - Lessons: refactoring/event-driven-lessons.md
      - Deposit Flow: refactoring/event-driven-deposit-flow.md
      - Stripe Webhook: payments/event-driven-stripe-webhook.md
      - Domain Events: domain-events.md
    - Dependency Injection:
      - Layered-dependency-injection: refactoring/layered-dependency-injection.md
  - API Reference:
    - api/index.md
    - Requests(REST Client):
      - requests/index.md
      - Account: requests/account.http
      - Currencies: requests/currencies.http
  - Blog:
    - blog/index.md
