package webapi

import (
	"time"

	"github.com/amirasaad/fintech/pkg/config"
	"github.com/amirasaad/fintech/pkg/service"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/limiter"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/swagger"

	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/amirasaad/fintech/docs"
)

func NewApp(
	accountSvc *service.AccountService,
	userSvc *service.UserService,
	authSvc *service.AuthService,
	currencySvc *service.CurrencyService,
	cfg *config.AppConfig,
) *fiber.App {
	app := fiber.New(fiber.Config{
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			// Default to 500 if status code cannot be determined
			status := fiber.StatusInternalServerError
			if e, ok := err.(*fiber.Error); ok {
				status = e.Code
			}
			return ErrorResponseJSON(c, status, "Internal Server Error", err.Error())
		},
	})
	app.Get("/swagger/*", swagger.New(swagger.Config{
		TryItOutEnabled:      true,
		WithCredentials:      true,
		PersistAuthorization: true,
	}))

	app.Use(limiter.New(limiter.Config{
		Max:        5,
		Expiration: 1 * time.Second,
		KeyGenerator: func(c *fiber.Ctx) string {
			return c.IP()
		},
		LimitReached: func(c *fiber.Ctx) error {
			return ErrorResponseJSON(c, fiber.StatusTooManyRequests, "Too Many Requests", "Rate limit exceeded")
		},
	}))
	app.Use(recover.New())

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("App is working! 🚀")
	})

	AccountRoutes(app, accountSvc, authSvc, cfg)
	UserRoutes(app, userSvc, authSvc, cfg)
	AuthRoutes(app, authSvc)
	CurrencyRoutes(app, currencySvc, authSvc, cfg)

	return app
}
