package webapi

import (
	"errors"
	"time"

	"github.com/amirasaad/fintech/pkg/apiutil"
	"github.com/amirasaad/fintech/pkg/config"
	accountsvc "github.com/amirasaad/fintech/pkg/service/account"
	authsvc "github.com/amirasaad/fintech/pkg/service/auth"
	currencysvc "github.com/amirasaad/fintech/pkg/service/currency"
	usersvc "github.com/amirasaad/fintech/pkg/service/user"
	"github.com/amirasaad/fintech/webapi/account"
	"github.com/amirasaad/fintech/webapi/auth"
	"github.com/amirasaad/fintech/webapi/currency"
	"github.com/amirasaad/fintech/webapi/user"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/limiter"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/swagger"

	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/amirasaad/fintech/docs"
)

func NewApp(
	accountSvc *accountsvc.AccountService,
	userSvc *usersvc.UserService,
	authSvc *authsvc.AuthService,
	currencySvc *currencysvc.CurrencyService,
	cfg *config.AppConfig,
) *fiber.App {
	return newAppWithRateLimit(accountSvc, userSvc, authSvc, currencySvc, cfg, 5, 1*time.Second)
}

func newAppWithRateLimit(
	accountSvc *accountsvc.AccountService,
	userSvc *usersvc.UserService,
	authSvc *authsvc.AuthService,
	currencySvc *currencysvc.CurrencyService,
	cfg *config.AppConfig,
	maxRequests int,
	expiration time.Duration,
) *fiber.App {
	app := fiber.New(fiber.Config{
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			return apiutil.ProblemDetailsJSON(c, "Internal Server Error", err)
		},
	})
	app.Get("/swagger/*", swagger.New(swagger.Config{
		TryItOutEnabled:      true,
		WithCredentials:      true,
		PersistAuthorization: true,
	}))

	app.Use(limiter.New(limiter.Config{
		Max:        maxRequests,
		Expiration: expiration,
		KeyGenerator: func(c *fiber.Ctx) string {
			return c.IP()
		},
		LimitReached: func(c *fiber.Ctx) error {
			return apiutil.ProblemDetailsJSON(c, "Too Many Requests", errors.New("rate limit exceeded"), fiber.StatusTooManyRequests)
		},
	}))
	app.Use(recover.New())

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("App is working! 🚀")
	})

	account.AccountRoutes(app, accountSvc, authSvc, cfg)
	user.UserRoutes(app, userSvc, authSvc, cfg)
	auth.AuthRoutes(app, authSvc)
	currency.CurrencyRoutes(app, currencySvc, authSvc, cfg)

	return app
}
