// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/amirasaad/fintech/pkg/domain/events"
	"github.com/amirasaad/fintech/pkg/eventbus"
	mock "github.com/stretchr/testify/mock"
)

// NewBus creates a new instance of Bus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bus {
	mock := &Bus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Bus is an autogenerated mock type for the Bus type
type Bus struct {
	mock.Mock
}

type Bus_Expecter struct {
	mock *mock.Mock
}

func (_m *Bus) EXPECT() *Bus_Expecter {
	return &Bus_Expecter{mock: &_m.Mock}
}

// Emit provides a mock function for the type Bus
func (_mock *Bus) Emit(ctx context.Context, event events.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Emit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, events.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Bus_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type Bus_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - event events.Event
func (_e *Bus_Expecter) Emit(ctx interface{}, event interface{}) *Bus_Emit_Call {
	return &Bus_Emit_Call{Call: _e.mock.On("Emit", ctx, event)}
}

func (_c *Bus_Emit_Call) Run(run func(ctx context.Context, event events.Event)) *Bus_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 events.Event
		if args[1] != nil {
			arg1 = args[1].(events.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Bus_Emit_Call) Return(err error) *Bus_Emit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Bus_Emit_Call) RunAndReturn(run func(ctx context.Context, event events.Event) error) *Bus_Emit_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type Bus
func (_mock *Bus) Register(eventType events.EventType, handler eventbus.HandlerFunc) {
	_mock.Called(eventType, handler)
	return
}

// Bus_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Bus_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - eventType events.EventType
//   - handler eventbus.HandlerFunc
func (_e *Bus_Expecter) Register(eventType interface{}, handler interface{}) *Bus_Register_Call {
	return &Bus_Register_Call{Call: _e.mock.On("Register", eventType, handler)}
}

func (_c *Bus_Register_Call) Run(run func(eventType events.EventType, handler eventbus.HandlerFunc)) *Bus_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 events.EventType
		if args[0] != nil {
			arg0 = args[0].(events.EventType)
		}
		var arg1 eventbus.HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(eventbus.HandlerFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Bus_Register_Call) Return() *Bus_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *Bus_Register_Call) RunAndReturn(run func(eventType events.EventType, handler eventbus.HandlerFunc)) *Bus_Register_Call {
	_c.Run(run)
	return _c
}
