@host = https://fintech-beryl-beta.vercel.app
POST {{host}}/user HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.mail",
    "username": "test",
    "password": "R4g&BejL5P3j"
}

### Login
# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "identity": "test",
    "password": "R4g&BejL5P3j"
}

### Create Account
# @name account 
POST {{host}}/account
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.$.token}}

{
    "currency": "USD"
}

### Deposit to account
# @name deposit
POST {{host}}/account/{{account.response.body.$.data.$.ID}}/deposit HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.$.token}}


{
    "amount": 100
}

### Withdraw from account
# @name withdraw
POST {{host}}/account/{{account.response.body.$.data.$.ID}}/withdraw HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.$.token}}


{
    "amount": 100
}

### List Transactions
# @name transactions
GET {{host}}/account/{{account.response.body.$.data.$.ID}}/transactions HTTP/1.1
Authorization: Bearer {{login.response.body.$.data.$.token}}


### Get Account Balance
# @name balance
GET {{host}}/account/{{account.response.body.$.data.$.ID}}/balance  
Authorization: Bearer {{login.response.body.$.data.$.token}}
