name: ci
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-arm-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
  build:
    name: build
    runs-on: ubuntu-arm-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Run gotestsum
        run: gotestsum --junitfile report.xml --format standard-quiet
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "report.xml" # Or specify a glob pattern if you have multiple files
        if: always() # Ensures the summary is displayed even if tests fail

