name: e2e
on:
  push:
    branches:
      - main
jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Run gotestsum (unit test)
        run: gotestsum --junitfile report.xml --format standard-quiet -- -p 12 -json ./webapi/...
        env:
          JWT_SECRET_KEY: secret
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "report.xml" # Or specify a glob pattern if you have multiple files
        if: always() # Ensures the summary is displayed even if tests fail
